Config = {}
Config.voertuigen = {
    {
        model = 'PolitieMotor', 
        blauw = {1},
        groen = {}, 
        oranje = {2}, 
        werk = {},
        volgachter = {4},
        stopvoor = {3},
        stopachter = {},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieTouran', 
        blauw = {1,7},
        groen = {5}, 
        oranje = {2,8}, 
        werk = {6},
        volgachter = {4},
        stopvoor = {3},
        stopachter = {},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieRS6', 
        blauw = {1},
        groen = {}, 
        oranje = {2}, 
        werk = {6},
        volgachter = {4},
        stopvoor = {3},
        stopachter = {},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieAudi', 
        blauw = {1},
        groen = {}, 
        oranje = {2}, 
        werk = {6},
        volgachter = {4},
        stopvoor = {3},
        stopachter = {5},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieAmarok', 
        blauw = {1},
        groen = {}, 
        oranje = {2}, 
        werk = {6},
        volgachter = {3},
        stopvoor = {5},
        stopachter = {4},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieVito', 
        blauw = {1},
        groen = {}, 
        oranje = {2}, 
        werk = {5},
        volgachter = {4},
        stopvoor = {3},
        stopachter = {7},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieKlasse', 
        blauw = {1},
        groen = {5}, 
        oranje = {2}, 
        werk = {6},
        volgachter = {4},
        stopvoor = {3},
        stopachter = {},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieAudiUnmarked', 
        blauw = {1,2},
        groen = {}, 
        oranje = {}, 
        werk = {},
        volgachter = {4},
        stopvoor = {},
        stopachter = {3},
        extraOn ={},
        pitje = {6,10},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieBmw', 
        blauw = {1,2},
        groen = {}, 
        oranje = {}, 
        werk = {},
        volgachter = {4},
        stopvoor = {},
        stopachter = {3},
        extraOn ={},
        pitje = {6,10},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'PolitieVelar', 
        blauw = {1,2},
        groen = {}, 
        oranje = {}, 
        werk = {},
        volgachter = {4},
        stopvoor = {},
        stopachter = {3},
        extraOn ={},
        pitje = {6,10},
        sirene = 'politie',
        controller = 'politie',
    },
    {
        model = 'AmbulanceSprinter', 
        blauw = {1,2,3,4,5},
        groen = {7}, 
        oranje = {6}, 
        werk = {},
        sirene = 'ambulance',
        controller = 'ambulance',
    },
    {
        model = 'AmbulanceTouran', 
        blauw = {1,6,7},
        groen = {3}, 
        oranje = {2,5}, 
        werk = {4},
        sirene = 'ambulance',
        controller = 'ambulance',
    },
    {
        model = 'AmbulanceAmarok', 
        blauw = {1,5},
        groen = {6}, 
        oranje = {8}, 
        werk = {9},
        sirene = 'ambulance',
        controller = 'ambulance',
    },
}
